### ISSUE TITLE
Problem returns infeasible when Excel OpenSolver and Gurobi can solve

### ISSUE THREAD

**Issue by eperrone-kercher** [coin-or/Cbc#380] opened 2021-04-05 18:33 UTC
Hello folks,
I have this small example problem MPS  (we are trying to solve a much larger but similarly structured problem) that CBC is reporting infeasible.  I was able to do the same problem in Excel OpenSolver using CBC and also with Gurobi via NeOS.  It seems that something is not working quite correctly.  Attaching the small MPS (in attached zip) file for the problem.

**Result from CBC is:**
Welcome to the CBC MILP Solver
Version: devel
Build Date: Feb 26 2021

command line - cbc.exe eric3.mps (default strategy 1)
At line 1 NAME          ERIC
At line 2 ROWS
At line 9 COLUMNS
At line 128 RHS
At line 134 ENDATA
Problem ERIC has 5 rows, 29 columns and 87 elements
Coin0008I ERIC read with 0 errors
Problem is infeasible - 0.00 seconds
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

**Result from Gurobi is:**
Using license file gurobi-client.lic
Set parameter TokenServer to value opt-license.discovery.wisc.edu Read MPS format model from file model.mps Reading time = 0.00 seconds
ERIC: 5 rows, 29 columns, 87 nonzeros

Checking threads settings... (NEOS allows a maximum of 4 threads) Changed value of parameter Threads to 4
   Prev: 0  Min: 0  Max: 1024  Default: 0 Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (linux64) Thread count: 12 physical cores, 24 logical processors, using up to 4 threads Optimize a model with 5 rows, 29 columns and 87 nonzeros Model fingerprint: 0x4ccabd79 Variable types: 0 continuous, 29 integer (0 binary) Coefficient statistics:
  Matrix range     [1e+02, 5e+05]
  Objective range  [3e+04, 5e+07]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+04, 1e+06]
Found heuristic solution: objective -6.83527e+07 Presolve removed 1 rows and 1 columns Presolve time: 0.02s
Presolved: 4 rows, 28 columns, 73 nonzeros Variable types: 0 continuous, 28 integer (28 binary)

Root relaxation: objective -7.373593e+07, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 -7.374e+07    0    1 -6.835e+07 -7.374e+07  7.88%     -    0s
H    0     0                    -7.02135e+07 -7.374e+07  5.02%     -    0s
H    0     0                    -7.25147e+07 -7.374e+07  1.68%     -    0s
H    0     0                    -7.26884e+07 -7.374e+07  1.44%     -    0s
H    0     0                    -7.30936e+07 -7.374e+07  0.88%     -    0s
H    0     0                    -7.33930e+07 -7.374e+07  0.47%     -    0s
     0     0 -7.367e+07    0    3 -7.339e+07 -7.367e+07  0.37%     -    0s
H    0     0                    -7.35799e+07 -7.367e+07  0.12%     -    0s
     0     0 -7.359e+07    0    1 -7.358e+07 -7.359e+07  0.01%     -    0s

Cutting planes:
  Gomory: 1
  Cover: 2
  MIR: 1

Explored 1 nodes (7 simplex iterations) in 0.06 seconds Thread count was 4 (of 24 available processors)

Solution count 7: -7.35799e+07 -7.3393e+07 -7.30936e+07 ... -6.83527e+07

Optimal solution found (tolerance 1.00e-04) Best objective -7.357988982960e+07, best bound -7.358688089080e+07, gap 0.0095%

********** Begin .sol file *************

# Solution for model ERIC
# Objective value = -7.3579889829599991e+07
X0000001 0
X0000002 0
X0000003 1
X0000006 1
X0000008 0
X0000009 1
X000000d 1
X0000015 1
X0000016 0
X0000018 1
X0000019 1
X0000020 0
X0000021 1
X000002a 1
X000002b 1
X0000033 0
X0000037 0
X000003e 1
X000003f 0
X0000042 1
X0000045 1
X0000049 1
X000004b 0
X000004c 1
X000004d 0
X000004e 1
X0000058 0
X0000066 1
X0000067 1

********** End .sol file ***************

[ERIC3.zip](https://github.com/coin-or/Cbc/files/6259917/ERIC3.zip)

**Comment by jjhforrest** [comment] 2021-04-06 08:33
The problem can not be seen with the naked eye!

The third rhs is actually    RHS\t    B14       1000000

The tab character was not taken as a blank (not free format) so the code 
thought that was the end of that rhs - so the problem is infeasible.

If I added FREE to NAME then it used free format and was fine.

It is probably safe to change \t to blank even in fixed MPS format. 
Thoughts on that?

John Forrest

**Comment by jjhforrest** [comment] 2021-04-06 12:53
Made one line change in CoinMpsIO.cpp in master.  Should fix problem.

**Comment by eperrone-kercher** [comment] 2021-04-06 12:57
Ah ha! Hiding right there.....  Thanks taking out that character did the trick.

**Comment by EmiFej** [comment] 2021-11-25 18:12
Is it possible to convert a Gurobi solution file (.sol) to a cbc output file (.txt)? In case you run the model with Gurobi but need the format to be cbc.txt for other purposes later?

**Comment by tkralphs** [comment] 2021-11-29 19:50
@EmiFej This question seems to be an unrelated to the original issue, which was resolved. I'm going to close this and you can feel free to post a new Discussion (this doesn't seem to be an Issue, really).

**Closed as completed by tkralphs** 2021-11-29 19:50 UTC
