### ISSUE TITLE
Stack smashing command line cbc

### ISSUE THREAD

**Issue by AndreaB2604** [coin-or/Cbc#230] opened 2019-05-22 21:38 UTC
Using the command line: if I use "?" in cbc with a verbose greater than or equal to 2 the progam end with a stack smashing error. I tried to change machine and reinstall from the source code, but nothing change. Running with valgrind, it reports a problem in CoinReadPrintit(char const*) (in CbcSolver.so.0.0.0). I can upload the log file if it can help.
Hope this can be useful.

**Comment by jjhforrest** [comment] 2019-05-23 09:49
Problem is not verbose itself.

The help for lift and project and reduce and split was very odd - so you 
get error with lift?

Hopefully fixed.

**Comment by svigerske** [comment] 2019-05-23 10:31
The problem is rather that the long help was too long for `CoinReadPrintit` to print it. That function assumes that input strings are at most 100 characters!

Fixed by https://projects.coin-or.org/Clp/changeset/2473/
Mirroring the Clp-svn to GitHub still seems to be broken, though (@tkralphs).

**Closed as completed by svigerske** 2019-05-23 10:31 UTC
