### ISSUE TITLE
CBC Error: “This application has requested the Runtime to terminate it in an unusual way.” solving mps

### ISSUE THREAD

**Issue by jwlevis** [coin-or/Cbc#226] opened 2019-05-15 07:28 UTC
I am trying to use cbc and/or symphony to solve an mps file. The file solves using CPLEX and GLPK. The file imports/loads into cbc/symphony without error, and I when I go to solve I get the error: "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information." Command line inputs and outputs below.

```
PS C:\Users\username\Google Drive\swolf - copy> cbc
Welcome to the CBC MILP Solver
Version: 2.8.8
Build Date: Dec 20 2013
Revision Number: 1998

CoinSolver takes input from arguments ( - switches to stdin)
Enter ? for list of commands or help
Coin:import SF_All.mps
At line 8 NAME          swolf_co
At line 9 ROWS
At line 3176864 COLUMNS
At line 9947442 RHS
At line 9947468 BOUNDS
At line 9947635 ENDATA
Problem swolf_co has 3176853 rows, 3455061 columns and 11718825 elements
Coin0008I swolf_co read with 0 errors
Coin:solv

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

So far, I've restarted everything and redownloaded\installed COIN-OR without any change. I have tried on multiple Windows 10 machines. Any advice you can give would be greatly appreciated.

I don't know if it matters, but I created the mps file using GLPK Mathprog model and data files. CBC has worked on smaller similar problems produced in this manner. The mps file is 410 MB and therefore can't be attached.

**Comment by svigerske** [comment] 2019-05-15 07:34
Cbc 2.8.8 is pretty old, as the log says. Why not try a current version? (https://bintray.com/version/files/coin-or/download/Cbc/2.10)

**Comment by jwlevis** [comment] 2019-05-15 08:18
Great point. I downloaded what I thought was the latest version of COINAll from here: https://www.coin-or.org/download/binary/CoinAll/ 

I did update to 2.10 (Cbc-2.10-x86_64-w64-mingw32.zip - I wasn't sure which version was ideal), and the only thing that has changed is that it no longer says "This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information." It just exits to the prompt:

```
PS C:\my_directory> cbc
Welcome to the CBC MILP Solver
Version: Trunk (unstable)
Build Date: May  3 2019

CoinSolver takes input from arguments ( - switches to stdin)
Enter ? for list of commands or help
Coin:import SF_All.mps
At line 8 NAME          swolf_co
At line 9 ROWS
At line 3176864 COLUMNS
At line 9947442 RHS
At line 9947467 BOUNDS
At line 9947634 ENDATA
Problem swolf_co has 3176853 rows, 3455061 columns and 11718825 elements
Coin0008I swolf_co read with 0 errors
Coin:integerT 0.5
integerTolerance was changed from 1e-07 to 0.5
Coin:solv
PS C:\my_directory> 
```

**Comment by jwlevis** [comment] 2019-05-16 14:40
Other times if finds the solution to the LP relaxation, which is integer optimal, but it just hangs. Sometimes is gets out and actually reports a solution (below), other times it just hangs indefinitely. 

```
C:\my_directory>cbc
Welcome to the CBC MILP Solver
Version: Trunk (unstable)
Build Date: May  3 2019

CoinSolver takes input from arguments ( - switches to stdin)
Enter ? for list of commands or help
Coin:verbose 15
verbose was changed from 0 to 15
Coin:import SF_STD.mps
At line 8 NAME          swolf_co
At line 9 ROWS
At line 179948 COLUMNS
At line 539250 RHS
At line 539271 BOUNDS
At line 539402 ENDATA
Problem swolf_co has 179937 rows, 191943 columns and 619924 elements
Coin0008I swolf_co read with 0 errors
Coin:stat
Presolve 18316 (-161621) rows, 19174 (-172769) columns and 138258 (-481666) elements
Statistics for presolved model
Original problem has 24 integers (24 of which binary)


Problem has 18316 rows, 19174 columns (2 with objective) and 138258 elements
There are 1 singletons with objective
Column breakdown:
19165 of type 0.0->inf, 6 of type 0.0->up, 0 of type lo->inf,
0 of type lo->up, 1 of type free, 0 of type fixed,
0 of type -inf->0.0, 2 of type -inf->up, 0 of type 0.0->1.0
Row breakdown:
9660 of type E 0.0, 0 of type E 1.0, 0 of type E -1.0,
1 of type E other, 6 of type G 0.0, 0 of type G 1.0,
1 of type G other, 8646 of type L 0.0, 0 of type L 1.0,
2 of type L other, 0 of type Range 0.0->1.0, 0 of type Range other,
0 of type Free
Coin:solv
Continuous objective value is 1.25864e+08 - 1.81 seconds
Cgl0002I 6 variables fixed
Cgl0004I processed model has 18298 rows, 19156 columns (0 integer (0 of which binary)) and 137182 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1.25864e+08 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                125864301.49648696
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             905.83
Time (Wallclock seconds):       905.85
```

**Comment by svigerske** [comment] 2019-05-31 15:54
I don't see what one could do from just seeing the output. There is nothing here to reproduce the issue.

**Comment by gdowdy3** [comment] 2019-06-12 17:34
I've been seeing the same error message.  But, in my case, whether or not it appears seems to be random.  This means that I don't know how to reproduce the issue.  It just happens sometimes.

**Comment by gdowdy3** [comment] 2019-06-12 17:41
I've also tried simply upgrading to the latest version of the software.  I found the same copy of the code that you referenced @svigerske ,  but I was unsure about using it, because of the "Trunk (unstable)" text that appears in place of the version number (see @jwlevis 's console output above).  Instead, I settled on version 2.9.9, which is also available on bintray.  Do you think that's a mistake @svigerske ?

**Comment by gdowdy3** [comment] 2019-06-12 17:44
I'm still doing some tests with 2.9.9 to see if upgrading eliminated the problem.  So far, so good.  Then again, since I don't know how to reproduce the error, my tests are inconclusive.  The more I run my code and don't see the error, the more *confident* I can be that the error has been eliminated, but I can never be sure that it won't pop up again in the future.

**Comment by tkralphs** [comment] 2019-06-12 18:35
The latest version on bintray is 2.10.0, so I would use that one. We are actually up to 2.10.2, but because of an unfortunate combination of minor glitches, no binaries are available for 2.10.1 and 2.10.2. They will be available again starting with 2.10.3.

**Comment by gdowdy3** [comment] 2019-06-12 20:24
@tkralphs , sorry for my tone, and thank you for the reminder that this is free software.  I've gone back and removed the unnecessary commentary from my previous posts.

Just to be clear, you would recommend that I use version 2.10.0 even though it declares itself to be "unstable"?

**Comment by tkralphs** [comment] 2019-06-13 17:35
OK, I see what you're saying now. For the life of me, I cannot figure out why the binaries that are uploaded as version 2.10.0 report that they are trunk. I checked all the logs and everything seemed to be normal. The sources that were used to build those binaries seem to be for the right version, the date it was uploaded is the right date, I'm at a loss. 

As of this moment, I would use version 2.10, which has all the latest fixes, though it is not an official release. We'll probably be releasing 2.10.3 today, so if you can wait, I would just look for that. I'll notify you here and then close this issue.

**Comment by tkralphs** [comment] 2019-06-13 17:39
And thank you for your understanding. We are trying to make things work as well as we can, given our limited resources!

**Comment by tkralphs** [comment] 2019-06-17 02:19
We finally managed to debug why the binaries for 2.10.0 were claiming to be trunk and that is now fixed. We also made release 2.10.3, so now you should be able to download binaries from bintray and give that one a try.  If you have problems, feel free to report them---just be aware that this particular error ("This application has requested the Runtime to terminate it in an unusual way") is a generic error that is Windows's way of just saying "Something went wrong, but we have no idea what." It's almost impossible to determine what went wrong simply from knowing that the run ended that way. If you can identify a particular instance that causes problems or a pattern of when it crashes, that gives us something to go on. Cheers!

**Closed as completed by tkralphs** 2019-06-17 02:19 UTC

**Comment by gdowdy3** [comment] 2019-06-17 04:18
I understand.  Thanks for the update, @tkralphs .
